_pimcore:
    resource: "@PimcoreCoreBundle/Resources/config/routing.yml"

my_trip:
    resource: "@MyTripBundle/Controller/"
    type:     annotation
    prefix:   /

members_auth:
    resource: '@MembersBundle/Resources/config/pimcore/routing/all.yml'
