app:
    resource: "@AppBundle/Controller/"
    type:     annotation

my_trip_update_step:
    path: /ajax/update-step
    defaults: { _controller: AppBundle\Controller\MyTripController::updateStep }

my_trip_remove_step:
    path: /ajax/remove-step
    defaults: { _controller: AppBundle\Controller\MyTripController::removeStep }

my_trip_load_step:
    path: /ajax/load-step
    defaults: { _controller: AppBundle\Controller\MyTripController::loadStep }

my_trip_load_geojson:
    path: /ajax/load-geo-json
    defaults: { _controller: AppBundle\Controller\MyTripController::loadGeoJson }

my_trip_get_next_date:
    path: /ajax/next-date
    defaults: { _controller: AppBundle\Controller\MyTripController::getNextDate }

