app:
    resource: "@AppBundle/Controller/"
    type:     annotation

my_trip_add_step:
    path: /ajax/add-step
    defaults: { _controller: AppBundle\Controller\MyTripController::addStep }

my_trip_load_step:
    path: /ajax/load-step
    defaults: { _controller: AppBundle\Controller\MyTripController::loadStep }

my_trip_load_steps:
    path: /ajax/load-steps
    defaults: { _controller: AppBundle\Controller\MyTripController::loadSteps }

my_trip_load_geojson:
    path: /ajax/load-geo-json
    defaults: { _controller: AppBundle\Controller\MyTripController::loadGeoJson }

