imports:
    - { resource: 'services/*.yml' }

services:
    # Templating
    AppBundle\Templating\LanguageSwitcher:
        arguments:
            - '@pimcore.document_service'

    # Twig Extensions
    AppBundle\Twig\Extension\AssetExtension:
        tags:
            - { name: twig.extension }

    AppBundle\Twig\Extension\StringExtension:
        tags:
            - { name: twig.extension }